### ISSUE TITLE
EAC binding for Windows is crashing the python.exe

### ISSUE THREAD

**Issue by psytester** [frankmorgner/openpace#18]
The simple test to start python interpreter and doing:
>>> import eac
>>> eac.EAC_init()

shows all is fine, I see the "Established PACE channel" Output. But the init is not really done, see add-on below.

With a lot of debug prints I pointed the problem to the call of function eac.CVC_get_chr(self.cvc) in eac.py.

If I add some prints there, I don't see the Outputs, the eac.CVC_get_chr() is never really called??!?:
def CVC_get_chr(_args):
   print “DEBUG: I’m in def CVC_get_chr(_args) and will return now with return _eac.CVC_get_chr(_args)” <--- this print is NOT shown!!!
   return _eac.CVC_get_chr(_args) 
print “DEBUG: will do now CVC_get_chr = _eac.CVC_get_chr”  <--- this print is shown during call of Init
CVC_get_chr = _eac.CVC_get_chr
print “DEBUG: done CVC_get_chr = _eac.CVC_get_chr”  <--- this print is shown during call of Init

If I add a print into the eac.EAC_init(), I don't see the output in that simple check
>>> import eac
DEBUG: …some additional output is shown….
>>> eac.EAC_init()
<--- this print „DEBUG: …“ output is missing

**Comment by frankmorgner** [comment]
Hmm, I'm a bit puzzled about what the actual problem is. `eac.EAC_init()` is only a swig wrapper to `EAC_init()` which means that it is possible that swig exits detecting a problem before it actually calls `EAC_init()`. However, could you describe what you are trying to do that is not working (and what the expected outcome would be)? Then I could reproduce the error to fix it...

**Comment by psytester** [comment]
Just start a vicc instance in nPA mode and while the startup or nPA is accessed from eID Client (I do not know anymore) the vicc Windows binary is crashing. Details I can give only in 3 weeks....

**Comment by frankmorgner** [comment]
I was just able to reproduce the problem with https://github.com/frankmorgner/openpace/blob/master/bindings/python/test.py . The segfault still persists in the current libeac. I will have a closer look at _eac.pyd ...

**Comment by psytester** [comment]
Hey Frank,
tomorrow in one month the issue has its 3rd birthday ;-)

**Comment by frankmorgner** [comment]
then I'll check back in one month 😜

**Comment by frankmorgner** [comment]
I've set up the whole build chain with VC, which fixes this issue. It seems that combining cross compiled libraries from MinGW-w64 and VC binaries, leads to some incompatibility.

You should be able to simply use the binaries of the next release.
