### ISSUE TITLE
Generating RSA cert chains

### ISSUE THREAD

**Issue by Tempelier** [frankmorgner/openpace#19]
Hello
Using the following steps :
1) generate CV private key : 
openssl pkcs8 -topk8 -nocrypt -in D:\OTATCVCA00001.pem -outform DER -out D:\OTATCVCA00001.pkcs8
=> ok
2) generate self signed cv-cert :
cvc-create --role=cvca --type=at --chr=OTATCVCA00001 --expires=160210 --issued=150210 --sign-with="D:\OTATCVCA00001.pkcs8" --scheme=RSA_v1_5_SHA_1 --write-dg17 --write-dg18 --write-dg19 --write-dg20 --write-dg21 --read-dg1 --read-dg2 --read-dg3 --read-dg4 --read-dg5 --read-dg6 --read-dg7 --read-dg8 --read-dg9 --read-dg10 --read-dg11 --read-dg12 --read-dg13 --read-dg14 --read-dg15 --read-dg16 --read-dg17 --read-dg18 --read-dg19 --install-qual-cert --install-cert --pin-management --can-allowed --privileged --rid --verify-community --verify-age
=> ok
3) generate dv-cert signed by cv, with autogenerated dv private key :

**Comment by Tempelier** [comment]
rewording all:
Hello
Using the following steps :
1) generate CV private key :
openssl genrsa -out D:\OTATCVCA00001.pem 2048
and
openssl pkcs8 -topk8 -nocrypt -in D:\OTATCVCA00001.pem -outform DER -out D:\OTATCVCA00001.pkcs8
=> ok
2) generate self signed cv-cert :
cvc-create --role=cvca --type=at --chr=OTATCVCA00001 --expires=160210 --issued=150210 --sign-with="D:\OTATCVCA00001.pkcs8" --scheme=RSA_v1_5_SHA_1 --write-dg17 --write-dg18 --write-dg19 --write-dg20 --write-dg21 --read-dg1 --read-dg2 --read-dg3 --read-dg4 --read-dg5 --read-dg6 --read-dg7 --read-dg8 --read-dg9 --read-dg10 --read-dg11 --read-dg12 --read-dg13 --read-dg14 --read-dg15 --read-dg16 --read-dg17 --read-dg18 --read-dg19 --install-qual-cert --install-cert --pin-management --can-allowed --privileged --rid --verify-community --verify-age
=> ok
3) generate dv-cert signed by cv, with autogenerated dv private key :
cvc-create --role=dv_domestic --type=at --chr=OTATDVCA00001 --expires=160210 --issued=150210 --sign-as="D:\OTATCVCA00001.cvcert" --sign-with="D:\OTATCVCA00001.pkcs8" --scheme=RSA_v1_5_SHA_1 --write-dg17 --write-dg18 --write-dg19 --write-dg20 --write-dg21 --read-dg1 --read-dg2 --read-dg3 --read-dg4 --read-dg5 --read-dg6 --read-dg7 --read-dg8 --read-dg9 --read-dg10 --read-dg11 --read-dg12 --read-dg13 --read-dg14 --read-dg15 --read-dg16 --read-dg17 --read-dg18 --read-dg19 --install-qual-cert --install-cert --pin-management --can-allowed --privileged --rid --verify-community --verify-age 
=> expecting to have a generated key pair for DV of same length as the CV, i.e. 2048
however, the DV key is generated with length=1024

if specifying
--key=`signer`
then the proper key is used, with its existing length. But this makes the DV have the same key as CV, which is not wanted.
Same issue appears when generating IS cert. and key.

Thank you for any feedback
Best regards

**Comment by frankmorgner** [comment]
This was fixed in 03e3d789be3b4a118e174ab1fcdf902a8514103d

**Comment by frankmorgner** [comment]
OK, with your mail I got your problem and I can confirm the problem.

One workaround would be to explicitly generate an 2048 RSA key for the DVCA (as you have done for the CVCA) and specify this during creation of the certificate ``cvc-create --role=dv_domestic ...  --key=DVCA_key.pkcs8``.

For a full fix I need to look deeper into the code...

**Comment by Tempelier** [comment]
Dear Frank

Thank you very much, I see that the update will correctly get the key parameters.

Unfortunately we are not well equiped – at my team level - to generate a build. When can a release of the (windows) exe be expected ?

Thank you

Best regards



De : Frank Morgner [mailto:notifications@github.com]
Envoyé : vendredi 13 mars 2015 10:22
À : frankmorgner/openpace
Cc : CREVEUIL Pierre
Objet : Re: [openpace] Generating RSA cert chains (#19)


Closed #19<https://github.com/frankmorgner/openpace/issues/19> via 0daa020<https://github.com/frankmorgner/openpace/commit/0daa020696bf35522f4028c77baa71612ad256f5>.

**Comment by frankmorgner** [comment]
sorry, I don't currently have the time. Either cross compile it yourself https://frankmorgner.github.io/openpace/install.html#compiling-for-windows or use the workaround described above https://github.com/frankmorgner/openpace/issues/19#issuecomment-78301741
