### ISSUE TITLE
Cross compilation for Android

### ISSUE THREAD

**Issue by jmailing** [frankmorgner/openpace#26]
Hi,

Thank you very much for the openpace library. I can make it work with Python and I think this is really nice.
I have tried to compile it for Android with Ubuntu 15.10 and Debian Wheezy.
I have tried with the github version and with the 0.9 and I could not manage to get it working.
I have had different issues and I was wondering whether you could just add some more things to the Android installation guide for newbees like me.
I am sorry not to be more specific because I have tried to fix things and now I am not sure anymore the errors I get are to be taken into consideration or whether they come from mistakes I have made.
Instead, I would very much need a more detailled howto.
Is the installation page based on the 0.9 release ?
Is there something I miss when I try
autoreconf --verbose --install
./configure --enable-openssl-install --prefix=$HOME/openpace
export MAKE_STANDALONE_TOOLCHAIN=~/Sdk/ndk-bundle/build/tools/make-standalone-toolchain.sh
make android

Any help would be very very appreciated !

Julien

_____________________________________________________________
The latest problem I have is with the rolling version

cvc_print-cvc-print-cmdline.o:cvc-print-cmdline.c:function cmdline_parser_params_create: error: undefined reference to 'rpl_malloc'
cvc_print-cvc-print-cmdline.o:cvc-print-cmdline.c:function gengetopt_strdup: error: undefined reference to 'rpl_malloc'
collect2: error: ld returned 1 exit status
Makefile:606: recipe for target 'cvc-print' failed
make[5]: *** [cvc-print] Error 1
make[5]: Leaving directory '/home/julien/Documents/Temporary/openpace/src'
Makefile:1105: recipe for target 'install' failed
make[4]: *** [install] Error 2
make[4]: Leaving directory '/home/julien/Documents/Temporary/openpace/src'
Makefile:516: recipe for target 'install-recursive' failed
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory '/home/julien/Documents/Temporary/openpace'
Makefile:567: recipe for target '/home/julien/Documents/Temporary/openpace/openpace-1.0.0_arm/lib/libeac.so' failed
make[2]: *** [/home/julien/Documents/Temporary/openpace/openpace-1.0.0_arm/lib/libeac.so] Error 2
make[2]: Leaving directory '/home/julien/Documents/Temporary/openpace/cross'
Makefile:552: recipe for target 'android' failed
make[1]: *** [android] Error 2
make[1]: Leaving directory '/home/julien/Documents/Temporary/openpace/cross'
Makefile:943: recipe for target 'android' failed
make: *** [android] Error 2

**Comment by frankmorgner** [comment]
Your problem should be solved with ca80088.

You're welcome to improve the documentation by submitting a pull request, e.g. somewhere around https://github.com/frankmorgner/openpace/blob/master/doc/install.txt.in#L121

**Comment by jmailing** [comment]
Thank you so much ! 
It seems to be working. I am going to try the compiled files. 
As for the documentation, unfortunately, it's because I don't have the knowledge to be sure of what I have to do that I did contact you after one day of digging. 

Best Regards, 

Julien 

----- Mail original -----

De: "Frank Morgner" <notifications@github.com> 
À: "frankmorgner/openpace" <openpace@noreply.github.com> 
Cc: "jmailing" <j.mailing@laposte.net> 
Envoyé: Lundi 14 Décembre 2015 20:34:02 
Objet: Re: [openpace] Cross compilation for Android (#26) 



Your problem should be solved with ca80088 . 

You're welcome to improve the documentation by submitting a pull request, e.g. somewhere around https://github.com/frankmorgner/openpace/blob/master/doc/install.txt.in#L121

**Comment by jmailing** [comment]
Just a quick followup. I am stuck again with the compilation giving me the following files in the lib directory: 
libeac.a libeac.la* libeac.so@ libeac.so.0@ libeac.so.0.0.0* pkgconfig/ python2.7/ 


Which file must I copy in Android Studio ? Have you heard of a test android application that would help me start ? 




Sorry for being so slow to understand :( 




Julien 


----- Mail original -----

De: "Frank Morgner" <notifications@github.com> 
À: "frankmorgner/openpace" <openpace@noreply.github.com> 
Cc: "jmailing" <j.mailing@laposte.net> 
Envoyé: Lundi 14 Décembre 2015 20:34:02 
Objet: Re: [openpace] Cross compilation for Android (#26) 



Your problem should be solved with ca80088 . 

You're welcome to improve the documentation by submitting a pull request, e.g. somewhere around https://github.com/frankmorgner/openpace/blob/master/doc/install.txt.in#L121

**Comment by frankmorgner** [comment]
what are you trying to do?

**Comment by jmailing** [comment]
I am working on a free passport reader application that is currently working on BAC passports and I am trying to add PACE mechanisms. 

----- Mail original -----

De: "Frank Morgner" <notifications@github.com> 
À: "frankmorgner/openpace" <openpace@noreply.github.com> 
Cc: "jmailing" <j.mailing@laposte.net> 
Envoyé: Mercredi 16 Décembre 2015 19:28:40 
Objet: Re: [openpace] Cross compilation for Android (#26) 



what are you trying to do?

**Comment by frankmorgner** [comment]
where is your sourcecode? maybe I can help with the integration.

You need JNI bindings for `libeac.so.0.0.0`. With `./configure --enable-java ...` we can already build them with SWIG, which is tested on desktops, but not on Android.

**Comment by jmailing** [comment]
For the moment, I don't have any public repository for the source code but I can zip it and send it to you. I will explain a little bit more the project if you want. Send an email to julien07 at gmail 



----- Mail original -----

De: "Frank Morgner" <notifications@github.com> 
À: "frankmorgner/openpace" <openpace@noreply.github.com> 
Cc: "jmailing" <j.mailing@laposte.net> 
Envoyé: Jeudi 17 Décembre 2015 08:50:22 
Objet: Re: [openpace] Cross compilation for Android (#26) 



where is your sourcecode? maybe I can help with the integration. 

You need JNI bindings for libeac.so.0.0.0 . With ./configure --enable-java ... we can already build them with SWIG, which is tested on desktops, but not on Android.

**Comment by frankmorgner** [comment]
Please notify me, when its public. I'll have a look then.

Am 17. Dezember 2015 09:02:57 MEZ, schrieb jmailing <notifications@github.com>:
>For the moment, I don't have any public repository for the source code
>but I can zip it and send it to you. I will explain a little bit more
>the project if you want. Send an email to julien07 at gmail 
>
>
>
>----- Mail original -----
>
>De: "Frank Morgner" <notifications@github.com> 
>À: "frankmorgner/openpace" <openpace@noreply.github.com> 
>Cc: "jmailing" <j.mailing@laposte.net> 
>Envoyé: Jeudi 17 Décembre 2015 08:50:22 
>Objet: Re: [openpace] Cross compilation for Android (#26) 
>
>
>
>where is your sourcecode? maybe I can help with the integration. 
>
>You need JNI bindings for libeac.so.0.0.0 . With ./configure
>--enable-java ... we can already build them with SWIG, which is tested
>on desktops, but not on Android. 
>
>— 
>Reply to this email directly or view it on GitHub . 
>
>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/frankmorgner/openpace/issues/26#issuecomment-165378386

-- 
Frank Morgner

**Comment by jmailing** [comment]
https://github.com/jmailing/openpace_android_studio_test 
This is the very beginning of a documentation project I would like to have on how to use Open PACE with Android Studio. 
Any help would be appreciated. 
I must have something wrong with the compilation. Do you think it is better to try to compile and use the 0.9 version or directly the git version ? 

Julien 

----- Mail original -----

De: "Frank Morgner" <notifications@github.com> 
À: "frankmorgner/openpace" <openpace@noreply.github.com> 
Cc: "jmailing" <j.mailing@laposte.net> 
Envoyé: Jeudi 17 Décembre 2015 09:05:22 
Objet: Re: [openpace] Cross compilation for Android (#26) 

Please notify me, when its public. I'll have a look then. 

Am 17. Dezember 2015 09:02:57 MEZ, schrieb jmailing <notifications@github.com>: 
>For the moment, I don't have any public repository for the source code 
>but I can zip it and send it to you. I will explain a little bit more 
>the project if you want. Send an email to julien07 at gmail 
> 
> 
> 
>----- Mail original ----- 
> 
>De: "Frank Morgner" <notifications@github.com> 
>À: "frankmorgner/openpace" <openpace@noreply.github.com> 
>Cc: "jmailing" <j.mailing@laposte.net> 
>Envoyé: Jeudi 17 Décembre 2015 08:50:22 
>Objet: Re: [openpace] Cross compilation for Android (#26) 
> 
> 
> 
>where is your sourcecode? maybe I can help with the integration. 
> 
>You need JNI bindings for libeac.so.0.0.0 . With ./configure 
>--enable-java ... we can already build them with SWIG, which is tested 
>on desktops, but not on Android. 
> 
>— 
>Reply to this email directly or view it on GitHub . 
> 
> 
> 
> 
>--- 
>Reply to this email directly or view it on GitHub: 
>https://github.com/frankmorgner/openpace/issues/26#issuecomment-165378386 

-- 
Frank Morgner
