### ISSUE TITLE
Sample project for Android Studio

### ISSUE THREAD

**Issue by jmailing** [frankmorgner/openpace#27]
Hi,

I wish you a very good 2016 year (postulate: you read that beginning of 2016)
I am trying to deploy Open PACE on Android Studio and I have come with this project so far : https://github.com/jmailing/openpace_android_studio_test
I am compiling for Android then copying all of the libraries in a .jar file.
Unfortunately, I get this error message:
java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libcrypto.so.1.0.0" needed by "libeac.so"; caused by library "libcrypto.so.1.0.0" not found
Does someone know:
- whether I should try to do a static compilation of openpace and the other libraries (is it painful for someone with no experience of makefiles ?)
- whether there is a trick so that Android takes all of the files included in the .jar into consideration and not only the .so files ?

Thank you for any piece of information !

**Comment by frankmorgner** [comment]
Have you tried using System.loadLibrary on libcrypto before loading the other libraries?

Am 4. Januar 2016 14:56:34 MEZ, schrieb jmailing <notifications@github.com>:
>Hi,
>
>I wish you a very good 2016 year (postulate: you read that beginning of
>2016)
>I am trying to deploy Open PACE on Android Studio and I have come with
>this project so far :
>https://githubcom/jmailing/openpace_android_studio_test
>I am compiling for Android then copying all of the libraries in a jar
>file
>Unfortunately, I get this error message:
>javalangUnsatisfiedLinkError: dlopen failed: could not load library
>"libcryptoso100" needed by "libeacso"; caused by library
>"libcryptoso100" not found
>Does someone know:
>- whether I should try to do a static compilation of openpace and the
>other libraries (is it painful for someone with no experience of
>makefiles ?)
>- whether there is a trick so that Android takes all of the files
>included in the jar into consideration and not only the so files ?
>
>Thank you for any piece of information !
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/frankmorgner/openpace/issues/27

-- 
Frank Morgner

**Comment by jmailing** [comment]
I have just tried with this code: 


public class eacJNI { 
static { 
System.loadLibrary("crypto"); 
System.loadLibrary("eac"); 
} 

Unfortunatley, the error code is the same. 

I don't know much about makefiles but is there a compilation option to only produce .so files and not the .so.1.0 and .so.1.0.0 files ? 

----- Mail original -----

De: "Frank Morgner" <notifications@github.com> 
À: "frankmorgner/openpace" <openpace@noreply.github.com> 
Cc: "jmailing" <j.mailing@laposte.net> 
Envoyé: Lundi 4 Janvier 2016 17:13:31 
Objet: Re: [openpace] Sample project for Android Studio (#27) 

Have you tried using System.loadLibrary on libcrypto before loading the other libraries? 

Am 4. Januar 2016 14:56:34 MEZ, schrieb jmailing <notifications@github.com>: 
>Hi, 
> 
>I wish you a very good 2016 year (postulate: you read that beginning of 
>2016) 
>I am trying to deploy Open PACE on Android Studio and I have come with 
>this project so far : 
>https://githubcom/jmailing/openpace_android_studio_test 
>I am compiling for Android then copying all of the libraries in a jar 
>file 
>Unfortunately, I get this error message: 
>javalangUnsatisfiedLinkError: dlopen failed: could not load library 
>"libcryptoso100" needed by "libeacso"; caused by library 
>"libcryptoso100" not found 
>Does someone know: 
>- whether I should try to do a static compilation of openpace and the 
>other libraries (is it painful for someone with no experience of 
>makefiles ?) 
>- whether there is a trick so that Android takes all of the files 
>included in the jar into consideration and not only the so files ? 
> 
>Thank you for any piece of information ! 
> 
> 
>--- 
>Reply to this email directly or view it on GitHub: 
>https://github.com/frankmorgner/openpace/issues/27 

-- 
Frank Morgner

**Comment by frankmorgner** [comment]
It seems there is already a fix to this http://git.savannah.gnu.org/cgit/libtool.git/commit/?id=8eeeb00daef8c4f720c9b79a0cdb89225d9909b6 which I have not applied in for the release binaries. I am not sure how to work around this without re-compiling the libraries...

**Comment by frankmorgner** [comment]
I think `System.load()` allows you to specify a full name, i.e. `libcrypto.so.1.0.0`

**Comment by jmailing** [comment]
It might but I don't know exactly how to include those so.1.0.0 into the gradle build system 
I have tried a lot of different options without any success. 
When I try to compile with the libtool patch, I get libeac.so without any other libeac.so.x.0 files but it sstill complains about libeac requesting libcrypto.so.1.0.0 


-> java.lang.UnsatisfiedLinkError: dlopen failed: could not load library "libcrypto.so.1.0.0" needed by "libeac.so"; caused by library "libcrypto.so.1.0.0" not found 

By chance, did you hear about any Android applications using the library ? 

Thank you for the help ! 




Julien 

----- Mail original -----

De: "Frank Morgner" <notifications@github.com> 
À: "frankmorgner/openpace" <openpace@noreply.github.com> 
Cc: "jmailing" <j.mailing@laposte.net> 
Envoyé: Lundi 4 Janvier 2016 17:49:26 
Objet: Re: [openpace] Sample project for Android Studio (#27) 



I think System.load() allows you to specify a full name, i.e. libcrypto.so.1.0.0

**Comment by frankmorgner** [comment]
I used OpenPACE only on the command line.

Creating libcrypto.so.1.0.0 is unfortunately done with the OpenSSL build system, not with libtool. It should be enough to simply remove the library version extension before creating OpenPACE.

For using a native library with gradle, please see http://lmgtfy.com/?q=gradle+android+native+so

**Comment by pekkal** [comment]
Hi,

I've been tinkering with OpenPACE and trying to make use of it Android Studio.  I managed to overcome the above problem by following the instructions given here:
http://stackoverflow.com/questions/33103867/unsatisfiedlinkerror-libcrypto-so-1-0-0-not-found
Basically just do the rpl command on the libjeac.so, libeac.so, and libcrypto.so.1.0.0.  Then rename the libcrypto.so.1.0.0 to libcrypto_1_0_0.so, and place these files to your android project. Then just do System.loadLibrary("jeac");.  A bit crude way, but it works.

However, this is not enough to make OpenPACE work in Android (or in Java in general) as the java classes are in default package and these classes cannot be accessed from any other package.  So, build process for java wrapper should generate java classes with a package name. This can be done by just editing the Makefile.am file in bindings/java directory.  (I see from Julien's project that this is what he has done.)

Anyway, by doing the above I've managed to access the OpenPACE library from an android application. But, this is still not enough. :-)

I want to use OpenPACE to negotiate PACE from device to smart card over NFC, but the problem is that there is no way to convert the SWIGTYPE_p_BUF_MEM to java's bytearray. This is needed as I want to communicate with a card to setup PACE on the java side.  Is there a way to do this conversion?  I haven't found it, or am I missing something?

Cheers,
Pekka

**Comment by frankmorgner** [comment]
Thanks for the update!

for conversion to BUF_MEM you can use ` get_buf`, for the other way round it would be `buf2string`. `get_buf` is also used in [the Java example](https://github.com/frankmorgner/openpace/blob/master/bindings/java/Example.java#L22).

**BUT** for communication via NFC you can also try something completely different:

1. Compile a PC/SC application that can do PACE for Android (you can use, for example, npa-tool from https://github.com/frankmorgner/OpenSC without modifications if all you want is PACE)
2. Compile the [PC/SC implementation with built-in vpcd](http://frankmorgner.github.io/vsmartcard/virtualsmartcard/README.html) for Android
3. Create a Android Java application that connects to the local Android's vpcd via TCP and relay the smart card communication via NFC.
4. Start the PC/SC application on Android's command line and watch the magic happen.

I've done this before, but it's a bit cumbersome for debugging and setting up...
