### ISSUE TITLE
Cross compile from Ubuntu (or Debian) to Windows

### ISSUE THREAD

**Issue by Bartzy** [frankmorgner/openpace#32]
### Expected behaviour

cross compilation to Windows should work according to the documentation.

What should happen?

`make win` should cross-compile the project to Windows. 

### Actual behaviour

I followed the documentation, trying Ubuntu 14.04 (failed OpenSSL version in ./configure - has 1.0.1 but 1.0.2 of libcrypto is requested), Debian Wheezy (same), and Ubuntu 16.04.

Ubuntu 16.04 compiles to linux correctly (simple `make`), but `make win` exits with an error after a lot of "undefined reference" errors (Entire `make win` output, including stdout and stderr is in the gist below).

All tests were done with vagrant boxes (ubuntu/trusty64, ubuntu/xenial64, debian/wheezy64).

### Logs

`make win` output is in this gist:
https://gist.github.com/Bartzy/062363856fc23b730c8c38b9d64abdda

Thanks!

**Comment by frankmorgner** [comment]
We have working cross compile builds from Ubuntu for Windows via [CI](https://travis-ci.org/frankmorgner/openpace). (Most recently: [x86](https://travis-ci.org/frankmorgner/openpace/jobs/256231953), [x64](https://travis-ci.org/frankmorgner/openpace/jobs/256231954))...

**Comment by frankmorgner** [comment]
Seems the script didn't build OpenSSL at the right time. Could you try `make -j1`?

**Comment by frankmorgner** [comment]
I mean `make -j1 win`
