### ISSUE TITLE
EJBCA can't parse CV certificate with extension

### ISSUE THREAD

**Issue by vorrarit** [frankmorgner/openpace#33]
### Expected behaviour
Normally the certificate can be read by cert-cvc

The certificate data should be printed out correctly.
7f21 CV_CERTIFICATE
   7f4e CERTIFICATE_BODY
      5f29 PROFILE_IDENTIFIER  0
      42 CA_REFERENCE  AT/DV_NXP/00001
      7f49 PUBLIC_KEY
         6 OID  0.4.0.127.0.7.2.2.2.2.1
         86 PUBLIC_POINT_Y  0473203DC23D908ABF572F3D8F2022172856A8B0C93FADB961BB5CD08A24185BDD58DA076C2440BA0C4C55F3C8727C8659
      5f20 HOLDER_REFERENCE  AT/IS_NXP/00001
      7f4c HOLDER_AUTH_TEMPLATE
         6 OID  0.4.0.127.0.7.3.1.2.1
         53 ROLE_AND_ACCESS_RIGHTS  03: IS/DG3+DG4
      5f25 EFFECTIVE_DATE  2015-06-10
      5f24 EXPIRATION_DATE  2016-06-10
   5f37 SIGNATURE  03A5309FDF0B67D0BF83C5D775EC90B8C72029629B5539D3A740FD38F28161929EF64E7D5923475D42E83BB8876A3681

### Actual behaviour

While read the certificate, I get the following stacktrace.

org.ejbca.cvc.exception.ParseException: Unknown CVC tag value 65
        at org.ejbca.cvc.CertificateParser.findTagFromValue(CertificateParser.java:135)
        at org.ejbca.cvc.CertificateParser.decode(CertificateParser.java:81)
        at org.ejbca.cvc.CertificateParser.decode(CertificateParser.java:100)
        at org.ejbca.cvc.CertificateParser.decode(CertificateParser.java:100)
        at org.ejbca.cvc.CertificateParser.decode(CertificateParser.java:63)
        at org.ejbca.cvc.CertificateParser.parseCertificate(CertificateParser.java:53)
        at com.pakgon.testcvc.App.loadCert(App.java:42)
        at com.pakgon.testcvc.App.main(App.java:52)

### Steps to reproduce

This java code simply load the certificate.

```
package com.pakgon.testcvc;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.security.InvalidKeyException;
import java.security.KeyFactory;
import java.security.NoSuchAlgorithmException;
import java.security.NoSuchProviderException;
import java.security.PrivateKey;
import java.security.Security;
import java.security.Signature;
import java.security.SignatureException;
import java.security.cert.CertificateException;
import java.security.spec.InvalidKeySpecException;
import java.security.spec.PKCS8EncodedKeySpec;

import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.ejbca.cvc.CVCertificate;
import org.ejbca.cvc.CardVerifiableCertificate;
import org.ejbca.cvc.CertificateParser;
import org.ejbca.cvc.exception.ConstructionException;
import org.ejbca.cvc.exception.ParseException;

public class App 
{
	private static byte[] loadFile(String filePath) throws IOException {
		File inFile = new File(filePath);
		FileInputStream inStream = new FileInputStream(inFile);
		int iInBufferRead = 0;
		int iInBufferOffset = 0;
		byte[] inBuffer = new byte[(int)inFile.length()];
		while ((iInBufferRead = inStream.read(inBuffer, iInBufferOffset, (int)(inFile.length()-iInBufferOffset))) > 0) {
			iInBufferOffset += iInBufferRead;
		}
		inStream.close();
		return inBuffer;
	}

	private static CVCertificate loadCert(String filePath) throws IOException, ParseException, ConstructionException {
		byte[] cert = loadFile(filePath);
		CVCertificate cvCertificate = (CVCertificate) CertificateParser.parseCertificate(cert);
		return cvCertificate;
	}

	public static void main( String[] args )
	{
		//sample usage for org.ejbca.cvc
		try {
			Security.addProvider(new BouncyCastleProvider());
			
			CVCertificate taCert = loadCert(
					"/path/to/file.cvcert");
			System.out.println(taCert.toString());

		} catch (IOException e) {
			e.printStackTrace();
		} catch (ParseException e) {
			e.printStackTrace();
		} catch (ConstructionException e) {
			e.printStackTrace();
		}
	}
}

```

**Comment by frankmorgner** [comment]
please attach the certificate in question.

**Comment by vorrarit** [comment]
Hi,

Here is the certificate.

[ATTA_NXP00001.cvcert.zip](https://github.com/frankmorgner/openpace/files/1207228/ATTA_NXP00001.cvcert.zip)

**Comment by frankmorgner** [comment]
The certificate looks good to me. Are you sure EJBCA is capable of handling certificate extensions (tag 65)?

Certificate extensions are optional, you may leave them out when creating certificates with `cvc-create`.

**Comment by vorrarit** [comment]
I'm also think that EJBCA does not support certificate extenstions.  Could you show me how to omit certificate extenstions when using cvc-create.  I've read the usage guide but cannot find one that is closed to.

**Comment by frankmorgner** [comment]
don't pass `--description` to `cvc-create`

**Comment by vorrarit** [comment]
Sorry but, I used the command as shown in the usage.html.  There's no --description.

> $ cvc-create --role=terminal --chr=ATTA_NXP00003 --expires=`date --date="next week" "+%^y%^m%^d"` --sign-with=DV_SHA1withECDSA_brainpoolp192r1.pkcs8 --sign-as=DV_SHA1withECDSA_brainpoolp192r1.cvcert --scheme=ECDSA_SHA_1 --rid --cert-desc=ZZATTERM00001.txt --issuer-name=ATDV_NXP00001 --subject-name=TERM3

I've also tried remove --cert-desc but get the following error

> cvc-create: '--issuer-name' option depends on option 'cert-desc'
> cvc-create: '--subject-name' option depends on option 'cert-desc'

**Comment by frankmorgner** [comment]
don't use ` --cert-desc=ZZATTERM00001.txt --issuer-name=ATDV_NXP00001 --subject-name=TERM3`

**Comment by vorrarit** [comment]
Hi,
Thank you for your help the certificate seem to work now.  However, I have problem loading the generated private key.  The error is

> InvalidKeySpecException: encoded key spec not recognized: wrong version for private key info

I'm not sure whether there's a way to set pkcs8 version in openpace or not.

**Comment by frankmorgner** [comment]
If you need a different private key format, use OpenSSL to convert the key...
