### ISSUE TITLE
Compilation fails when using OpenSSL 1.1.0 in Windows

### ISSUE THREAD

**Issue by lmiguelmh** [frankmorgner/openpace#34]
### Expected behaviour

What should happen?
The compilation process should not have errors.
**When using OpenSSL 1.0.2 the compilation doesn't fail**

### Actual behaviour

What happens instead?
A lot of errors like these in `ssl_compat.h` and `misc.h`:
```
c:\clibs\openpace\openpace-1.0.2\src\ssl_compat.h(51): error C2059: syntax error: 'string'
c:\clibs\openpace\openpace-1.0.2\src\ssl_compat.h(51): error C2059: syntax error: 'constant'
...
c:\clibs\openpace\openpace-1.0.2\src\misc.h(93): error C2143: syntax error: missing '{' before '*'
...
c:\clibs\openpace\openpace-1.0.2\src\ssl_compat.h(51): error C2059: syntax error: 'string'
c:\clibs\openpace\openpace-1.0.2\src\ssl_compat.h(51): error C2059: syntax error: 'constant'
...
```

### Steps to reproduce

Follow the steps for compilation detailed in: https://github.com/OpenSC/OpenSC/wiki/Compiling-on-Windows
1. Download and unpack the source code of the latest release of OpenPACE. 
2. Open a Visual Studio Developer Command Prompt and change to the OpenPACE’s src directory. 
3. Compile the library:

```
set OPENSSL=C:\OpenSSL-Win64
cl /I%OPENSSL%\include /I. /DX509DIR=\`"/\`" /DCVCDIR=\`"/\`" /W3 /D_CRT_SECURE_NO_DEPRECATE /DWIN32_LEAN_AND_MEAN /GS /MT /c ca_lib.c cv_cert.c cvc_lookup.c x509_lookup.c eac_asn1.c eac.c eac_ca.c eac_dh.c eac_ecdh.c eac_kdf.c eac_lib.c eac_print.c eac_util.c misc.c pace.c pace_lib.c pace_mappings.c ri.c ri_lib.c ta.c ta_lib.c objects.c
```

**Comment by frankmorgner** [comment]
https://github.com/OpenSC/OpenSC/wiki/Compiling-on-Windows is written for OpenSSL 1.0.0

Compile with the following additional flags: `/DHAVE_ASN1_STRING_GET0_DATA=1 /DHAVE_DECL_OPENSSL_ZALLOC=1 /DHAVE_DH_GET0_KEY=1 /DHAVE_DH_GET0_PQG=1 /DHAVE_DH_SET0_KEY=1 /DHAVE_DH_SET0_PQG=1 /DHAVE_ECDSA_SIG_GET0=1 /DHAVE_ECDSA_SIG_SET0=1 /DHAVE_EC_KEY_METHOD=1 /DHAVE_RSA_GET0_KEY=1 /DHAVE_RSA_SET0_KEY=1` for OpenSSL 1.1.0+

**Comment by lmiguelmh** [comment]
Thanks! This is the final command. Notice the changes from ``/DX509DIR=\`"/\`" /DCVCDIR=\`"/\`"`` to `/DX509DIR=\"/\" /DCVCDIR=\"/\"`:
```
C:\CLIBS\openpace\openpace-1.0.2\src>cl /I%OPENSSL%\include /I. /DX509DIR=\"/\" /DCVCDIR=\"/\" 
/W3 /D_CRT_SECURE_NO_DEPRECATE /DWIN32_LEAN_AND_MEAN /DHAVE_ASN1_STRING_GET0_DATA=1 /DHAVE_DECL_OPENSSL_ZALLOC=1 /DHAVE_DH_GET0_KEY=1 /DHAVE_DH_GET0_PQG=1 /DHAVE_DH_SET0_KEY=1 /DHAVE_DH_SET0_PQG=1 /DHAVE_ECDSA_SIG_GET0=1 /DHAVE_ECDSA_SIG_SET0=1 /DHAVE_EC_KEY_METHOD=1 /DHAVE_RSA_GET0_KEY=1 /DHAVE_RSA_SET0_KEY=1 /GS /MT /c ca_lib.c cv_cert.c cvc_lookup.c x509_lookup.c eac_asn1.c eac.c eac_ca.c eac_dh.c eac_ecdh.c eac_kdf.c eac_lib.c eac_print.c eac_util.c misc.c pace.c pace_lib.c pace_mappings.c ri.c ri_lib.c ta.c ta_lib.c objects.c
```
