### ISSUE TITLE
Links to pre-compiled binaries does not work

### ISSUE THREAD

**Issue by smuda** [frankmorgner/openpace#36]
### Expected behaviour
On the page [https://frankmorgner.github.io/openpace/install.htm](https://frankmorgner.github.io/openpace/install.html), when clicking the links for Win32 or Win64 pre-compiled binaries it should download a zip-filen with the pre-compiled binaries for windows.

### Actual behaviour
An error is received from the server:
```XML
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:a546a908-701e-00e7-516f-74aae9000000 Time:2018-11-04T18:53:20.0000378Z
</Message>
</Error>
```

### Steps to reproduce

1. Click the link. 
2. Get the error message.

**Comment by frankmorgner** [comment]
Please use the release instead of the development version.
