### ISSUE TITLE
openpace does not build in fedora environment

### ISSUE THREAD

**Issue by usual-user** [frankmorgner/openpace#37]
Trying to build oppenpace in fedora environment according to docs/install.html

./configure terminates with:

openpace 1.0.3 has been configured with following options:

Libraries:               /usr/local/lib
CVC directory:           /usr/local/etc/eac/cvc
X.509 directory:         /usr/local/etc/eac/x509

Host:                    armv7l-unknown-linux-gnueabihf
Compiler:                gcc
Preprocessor flags:
Compiler flags:          -g -O2
Linker flags:
Libraries:
CRYPTO_CFLAGS:
CRYPTO_LIBS:             -lcrypto

HELP2MAN:                /usr/bin/help2man
GENGETOPT:               /usr/bin/gengetopt

but make bails out with this:

make[4]: Entering directory 'openpace/src'

  CC       libeac_la-eac_util.lo
eac_util.c: In function â..Compâ..:
eac_util.c:792:25: warning: implicit declaration of function â..EC_POINT_get_affine_coordinates_GF2mâ..; did you mean â..EC_POINT_get_affine_coordinates_GFpâ..? [-Wimplicit-function-declaration]
  792 |                     || !EC_POINT_get_affine_coordinates_GF2m(group, ecp, x, y, bn_ctx))
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         EC_POINT_get_affine_coordinates_GFp
  CC       libeac_la-misc.lo
  CC       libeac_la-pace.lo

  CCLD     libvc.la
  CCLD     eactest
/usr/bin/ld: ./.libs/libeac.so: undefined reference to `EC_POINT_get_affine_coordinates_GF2m'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:709: eactest] Error 1
make[4]: Leaving directory 'openpace/src'

what am I missing?

**Comment by frankmorgner** [comment]
what's your OpenSSL version?

**Comment by usual-user** [comment]
fedora provides currently openssl-1.1.1a-2.fc30.armv7hl.rpm

Figured already the package is configured with no-ec2m
 (see [openssl.spec](https://src.fedoraproject.org/rpms/openssl/blob/master/f/openssl.spec#_235) for reference), but rebuilding the package with no-ec2m removed bails out with:
/usr/bin/ld: ./libcrypto.so: undefined reference to `EC_GF2m_simple_method'
/usr/bin/ld: ./libcrypto.so: undefined reference to `ec_GF2m_simple_point2oct'
/usr/bin/ld: ./libcrypto.so: undefined reference to `ec_GF2m_simple_set_compressed_coordinates'
/usr/bin/ld: ./libcrypto.so: undefined reference to `ec_GF2m_simple_oct2point'

As I don't know what I am doing and tinkering with some build options for testing is ok,
but I think red hat has some reason to have this disabled.
Some "DEPRECATEDIN_1_2_0" wrappers around the functions also seem to indicate not to use them any longer.

**Comment by frankmorgner** [comment]
Please check whether https://github.com/frankmorgner/openpace/pull/38 fixes the problem

**Comment by usual-user** [comment]
The deprecated branch still errors out (see [configure.log](https://github.com/frankmorgner/openpace/files/2912018/configure.log), [make.log](https://github.com/frankmorgner/openpace/files/2912019/make.log)  for reference)
With ssl_compat.c from master dropped in, make terminates flawless.

**Comment by usual-user** [comment]
Seems some "HAVE_" is missing (see [ssl_compat.txt](https://github.com/frankmorgner/openpace/files/2912277/ssl_compat.txt) for reference)

**Comment by frankmorgner** [comment]
thanks, I've merged the fix with master

**Comment by usual-user** [comment]
The master branch is now building against the current native fedora openssl package flawless.
The build instructions given in docs/install.html are approved to work in fedora environment.
Thank you for making the openpace code future-proof.
