### ISSUE TITLE
openpace does not work in fedora environment

### ISSUE THREAD

**Issue by usual-user** [frankmorgner/openpace#39]
I have composed a SPEC file to build for fedora environment suitable RPM packages.
While doing so I guess, I have spotted some builddir artefacts that "make install" is dropping in (see [openpace.spec](https://github.com/frankmorgner/openpace/files/2923040/openpace.spec.txt) section cleanup BUILDROOT for reference).
The SPEC file is far from perfect, but it builds usable RPM packages without errors.

With the packages installed eactest ist crashing (see [eactest.log](https://github.com/frankmorgner/openpace/files/2923041/eactest.log) for reference).
opensc is rebuild with npa-tool support, but npa-tool is erroring out with the same [ERROR] ... lines as eactest.
As I do not know the propper use of this tools till now it is maybe an user fault.

**Comment by frankmorgner** [comment]
It looks like your version of OpenSSL doesn't include the brainpool curves, which are typically used for EAC (but they are not the only possibilities).

Something like this code from eac_ecdh.c seems to fail:
```c
            tmp = EC_KEY_new_by_curve_name(NID_brainpoolP192r1);
```
That's strange, because the brainpool curves are included since OpenSSL 1.0.2 without an option to deactivate them...

The double free, however, should not happen in any case. If you submit the output of `valgrind eactest` with compiled debug symbols, I can have a look at this.

**Comment by frankmorgner** [comment]
Could it be that the runtime library of OpenSSL for eactest is older than 1.0.2?

**Comment by usual-user** [comment]
As the fedora [openssl.spec](https://src.fedoraproject.org/rpms/openssl/blob/master/f/openssl.spec) file does some modifications while building the package, maybe some have to be backed out:
Functionality changes
Patch31: openssl-1.1.1-conf-paths.patch
Patch32: openssl-1.1.1-version-add-engines.patch
Patch33: openssl-1.1.0-apps-dgst.patch
Patch36: openssl-1.1.1-no-brainpool.patch
Patch37: openssl-1.1.1-ec-curves.patch
Patch38: openssl-1.1.1-no-weak-verify.patch
Patch40: openssl-1.1.1-disable-ssl3.patch
Patch41: openssl-1.1.1-system-cipherlist.patch
Patch42: openssl-1.1.1-fips.patch
Patch43: openssl-1.1.1-ignore-bound.patch
Patch44: openssl-1.1.1-version-override.patch
Patch45: openssl-1.1.1-weak-ciphers.patch
Patch46: openssl-1.1.1-seclevel.patch
Patch48: openssl-1.1.1-fips-post-rand.patch
Patch49: openssl-1.1.1-evp-kdf.patch
Patch50: openssl-1.1.1-ssh-kdf.patch

I have never used valgrind nor do I know how to compile with debug symbols. But after installing some debug packages, I got for free while building the openpace packages, some question marks in the [valgrind-eactest.log](https://github.com/frankmorgner/openpace/files/2928186/valgrind-eactest.log) got filled in. Hope it is what you are looking for.

**Comment by frankmorgner** [comment]
I don't understand why all people are messing with OpenSSL. If I were you, I'd write a bug report at your distro for removing `openssl-1.1.1-no-brainpool.patch`. I don't see a single benifit of this patch.

The valgrind output looks OK, I'll have a look.

**Comment by frankmorgner** [comment]
Do you use the current master?
```
==24789== Invalid write of size 4
==24789==    at 0x48FF518: OPENSSL_cleanse (armv4cpuid.S:73)
==24789==  Address 0x5803b60 is 0 bytes inside a block of size 32 free'd
==24789==    at 0x4848CD0: free (vg_replace_malloc.c:540)
==24789==    by 0x4935DFB: BN_free (bn_lib.c:173)
==24789==    by 0x4891B87: Comp (eac_util.c:810)
==24789==    by 0x110F0F: dynamic_eac_test (eactest.c:2657)
==24789==    by 0x110F0F: do_dynamic_eac_tests (eactest.c:2908)
==24789==    by 0x10B387: main (eactest.c:3790)
==24789==  Block was alloc'd at
==24789==    at 0x4847690: malloc (vg_replace_malloc.c:309)
==24789==    by 0x49DBFDF: CRYPTO_zalloc (mem.c:230)
==24789==    by 0x4935E6B: bn_expand_internal (bn_lib.c:224)
==24789==    by 0x4935E6B: bn_expand2 (bn_lib.c:248)
==24789==    by 0x4935E6B: bn_expand2 (bn_lib.c:245)
==24789==    by 0x4935087: bn_set_words (bn_intern.c:190)
==24789==    by 0x49A7EDF: ecp_nistz256_get_affine.part.0 (ecp_nistz256.c:1377)
==24789==    by 0x49A8A63: ec_GFp_simple_point2oct (ecp_oct.c:209)
==24789==    by 0x489359B: EC_POINT_point2mem (misc.c:290)
==24789==    by 0x488E03B: ecdh_generate_key (eac_ecdh.c:123)
==24789==    by 0x10FA17: dynamic_eac_test (eactest.c:2610)
==24789==    by 0x10FA17: do_dynamic_eac_tests (eactest.c:2908)
==24789==    by 0x10B387: main (eactest.c:3790)
```
There is no call of BN_free in line 810...:
https://github.com/frankmorgner/openpace/blob/516336734baa5c35d2548c32926d480429f735d4/src/eac_util.c#L810

**Comment by frankmorgner** [comment]
I think you're missing this patch https://github.com/frankmorgner/openpace/commit/89b57fe5d981e2c075ddd0a9db19f1c83625a519

Looks like you need a self compiled version of OpenSSL (**with** brainpool curves) and an updated openpace!

**Comment by usual-user** [comment]
Took a little longer to get all loose ends sorted, but it is done now.
Looks like fedora has to rip out some code for legality reasons:
>  Clean out patent-or-otherwise-encumbered code.
>  MDC-2: 4,908,861 13/03/2007 - expired, we do not remove it but do not enable it anyway
>  IDEA:  5,214,703 07/01/2012 - expired, we do not remove it anymore
>  RC5:   5,724,428 01/11/2015 - expired, we do not remove it anymore
>  EC:    ????????? ??/??/2020
>  SRP:   ????????? ??/??/2017 - expired, we do not remove it anymore

As openpace depends on this it can also not land in fedora till this constraint expires.
So for now rebuilding of openssl packages with a mainline release tar ball dropped
in and [openssl.spec.diff](https://github.com/frankmorgner/openpace/files/2949955/openssl.spec-1.1.1b-2.diff.txt) applied is the way to go. The openpace packages have to be
build and for npa-tool support the opensc packages with [opensc.spec.diff](https://github.com/frankmorgner/openpace/files/2949956/opensc.spec-0.19.0-5.diff.txt) applied have
to be rebuild. See [howto-build-openpace-support.txt](https://github.com/frankmorgner/openpace/files/2949957/howto-build-openpace-support.txt) for some more in detail description.

For openpace I am using git master. But to approve the usability of the openpace.spec with
a release tar ball, I used  openpace-1.0.3.tar.gz with the "depricated api" commit mangled
in. There is no proper release tar ball available jet ;-). Seems I have somehow managed to
install these packages for further function tests. With the packages build from git master
the chrash is gone and eactest terminates now with "Everything works as expected.".
The npa-tool errors out with "Error: Card command failed" but for this openpace is probably
not to blame.

**Comment by frankmorgner** [comment]
Great!

Generate an OpenSC debug log and I'll handle the issue within the OpenSC project.
