### ISSUE TITLE
OpenPace with PKCS11 HSM

### ISSUE THREAD

**Issue by Alexseregin4** [frankmorgner/openpace#43]
Hello,

Is there any way to use OpenPace with PrivateKey on PKCS11 HSM.
Thanks.

**Comment by frankmorgner** [comment]
Could you be more specific?

**Comment by Alexseregin4** [comment]
Hi. 
My task is to make country verifying CA for Identity Cart. In test environment i use openssl, cvc-create and private key in file. 
But on production we need to use HSM device for generate keys, sign sertificate and DV request sign. For key generation i use OpenSSL and lib11. 
Is there any way to use cvc-create comand to create self signed CVCA and sign DV request with private key on HSM (Safenet PSE2)

Thanks

**Comment by frankmorgner** [comment]
In theory, OpenPACE supports using PKCS#11 via OpenSSL's engine plugins. https://github.com/OpenSC/libp11 provides such mapping, for example. Last year, there has also been some new approach available https://github.com/openssl/openssl/pull/8200.

Although OpenPACE allows specifying an engine for all sorts of keys, we have not actually tested that. Also, this functionality is not (yet) available via the command line tools cvc-create. However, I think adding support for this should be fairly straight forward.
1. add PKCS#11 module to openssl.conf
2. change the command line tools to support engines, as in the [`openssl` command](https://github.com/OpenSC/libp11#using-p11tool-and-openssl-from-the-command-line). Copy (some of) the initialization code [from OpenSSL](https://github.com/openssl/openssl/blob/master/apps/engine.c) to our tools.
3. [Propagate the engines to OpenPACE internal structures, when using the terminals private key](https://github.com/frankmorgner/openpace/blob/70c44a0e85fa7a20a1129f1785e4d7e814cf57b5/src/eac/eac.h#L250) before using them in the command line tools.
