### ISSUE TITLE
DV Certificate contain Domain Parameters

### ISSUE THREAD

**Issue by Alexseregin4** [frankmorgner/openpace#45]
### Expected behaviour

I have DV CSR file from another DV software. I use cvc-create with csr mode, but new DV certificate contain Domain Paremeters.
(BSI TR-03110-3 sad that DV MUST NOT contain domain parametrs).
What i do wrong? Thanks!

### Steps to reproduce
Files [https://drive.google.com/file/d/1UdkwhDqfUnp4eUNLpm6Eom37QB81IrU8/view?usp=sharing](url)
NEWKEY.pkcs8 - private key for CVCA cert
BYCVBY1.cvcert - CVCA cert
BYNCESBY00B.cvreq - DV CSR file
BYNCESBY00B.cvcert - wrong DV cert 

I used command: cvc-create --role=dv_domestic --type=is  --csr=BYNCESBY00B.cvreq --expires=201231 --sign-with=NEWKEY.pkcs8 --scheme=ECDSA_SHA_256 --read-finger --read-iris --rid

**Comment by frankmorgner** [comment]
well, you could argue that the CSR should not contain explicit parameters either then. Anyway, I've pushed a workaround for this special case.
