### ISSUE TITLE
GPL license when used with OpenSC 

### ISSUE THREAD

**Issue by pombredanne** [frankmorgner/openpace#46]
I have a question wrt. licensing
- OpenPACE is GPL-licensed
- OpenSC is using the LGPL license

OpenSC is configured to use OpenPACE as a dependency per https://github.com/OpenSC/OpenSC/blob/219c6cc49464c627c7741a2c17171d7f61fa536c/win32/Make.rules.mak#L117

My understanding is that when this happens the GPL would likely apply to the entire combination of OpenSC and OpenPACE.

Would it be possible to consider some alternative license for OpenPACE when used in OpenSC such as the LGPL or a GPL with linking exception such that OpenSC LGPL continues to apply?

@frankmorgner ping: I understand that you might be the primary maintainer of both tools 
@Jakuje ping 

Thank you for your kind consideration and this fine tool!

**Comment by pombredanne** [comment]
BTW, a related concern is that you are using OpenSSL which has a license that is not compatible with the GPL. 

See the bottom of https://scancode-licensedb.aboutcode.org/openssl-ssleay.html :
> The licence and distribution terms for any publically available version or
> derivative of this code cannot be changed.  i.e. this code cannot simply be
> copied and put under another distribution licence
> **[including the GNU Public Licence.]**

Typically GPL-licensed projects that depend on OpenSLL grant an exception for this. 
This is an example of such an exception
https://scancode-licensedb.aboutcode.org/gpl-2.0-openssl.html

May be here the same is required and while at it the exception could cover usage with OpenSC and OpenSSL ?

**Comment by frankmorgner** [comment]
Thanks for the reminder. I'm not a lawyer, but your concerns seem to be valid. If necessary, I can grant needed exceptions for OpenSC and OpenSSL. However, I'm hesitating to copy random stuff from the internet, even if labeled with *lawyer approved*. Do you have any legal problems with the current state that need to be solved?

**Comment by pombredanne** [comment]
@frankmorgner Thanks for the quick reply!

> Do you have any legal problems with the current state that need to be solved?

There no legal problems per se, but the current conflicts between the GPL here, the LGPL at OpenSC and the OpenSSL license means to me that I cannot use this at all until resolved

Granting an exception would be awesome. I am not a lawyer but definitely a FOSS license nerd, a co-founder of SPDX at the Linux Foundation and I helped a bit clarify licensing in the linux kernel https://github.com/pombredanne/gpl-history

So if I can help you, I will!
My advice would be to reuse almost exactly the texts of the GPL exception(s) granted by the FSF for their own projects. If you trust the GPL to the FSF then you can likely trust them for the exceptions too.

**Comment by pombredanne** [comment]
@frankmorgner here are some examples (and this https://scancode-licensedb.aboutcode.org is not a random web site: I am the primary maintainer ... therefore I would object to calling this random ;) ).

I can think of two ways:
1. grant an exception only for OpenSC and OpenSSL
2. grant a generic exception that is not specific to any library 

For the specific case see:

- First the FSF guidelines https://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs
IMHO that should be your first stop. This is here https://scancode-licensedb.aboutcode.org/gpl-3.0-linking-exception.html

- Then there are many examples of OpenSSL-specific exceptions: there is a good discussion here https://people.gnome.org/~markmc/openssl-and-the-gpl.html
  - https://scancode-licensedb.aboutcode.org/openssl-exception-gpl-3.0-plus : This is used by Tildeslash in monit: https://bitbucket.org/tildeslash/monit/src/c60f8726ed0823ebc12cc29196a7c8fd763d0851/COPYING#lines-663
  - https://scancode-licensedb.aboutcode.org/openssl-exception-gpl-2.0 ... and there are other variants.

For the generic case see:

-  you can grant a more generic exception to linking. Some GNU projects examples are:
   - GCC https://scancode-licensedb.aboutcode.org/gpl-3.0-gcc.html which is somewhat verbose but widely used
   - wget https://scancode-licensedb.aboutcode.org/gpl-3.0-linking-source-exception.html which is simple and neat

--
Cordially

**Comment by pombredanne** [comment]
@frankmorgner I hope the comments above are helping somehow.

**Comment by pombredanne** [comment]
@frankmorgner Sorry to bug you persistently, but have made up your mind or what's the direction you are likely to go?
Thank you!

**Comment by pombredanne** [comment]
@frankmorgner gentle ping ... I am a persistent bugger! I guess I should use an exponential backoff of sorts to ping you less and and less frequently to avoid being too annoying?

**Comment by pombredanne** [comment]
@frankmorgner I missed this in the noise of other notice. Thank you ++ for following through!
You rock
