### ISSUE TITLE
Problems compiling openpace under alpine linux

### ISSUE THREAD

**Issue by dominikheinz** [frankmorgner/openpace#51]
### Expected behaviour
It should compile without any errors.

### Actual behaviour
It doesnt compile. (See details below)

### Steps to reproduce

1. Setup a dockerfile with the following content:
```Dockerfile
FROM alpine:latest

WORKDIR /app

# Install general dependencies etc
RUN apk add python3
RUN python3 -m ensurepip
RUN apk add g++
RUN apk add git
RUN apk add gcc

# Install openpace
RUN apk add autoconf
RUN apk add automake
RUN apk add libtool
RUN apk add file
RUN apk add help2man
RUN apk add gengetopt
RUN apk add make
RUN apk add openssl
RUN apk add openssl-dev

RUN cd /app && git clone -b master https://github.com/frankmorgner/openpace.git
RUN cd openpace && autoreconf --verbose --install && ./configure --enable-openssl-install && make && make install

# Port configurations
EXPOSE 5000
```
2. Build the docker image 
3. The following error occurs during the compilation stage:

```
...
make[4]: Entering directory '/app/openpace/src'
  CC       eactest-eactest.o
In file included from eactest.c:51:
misc.h:111:7: error: unknown type name 'ECDH_METHOD'
  111 | const ECDH_METHOD *ECDH_OpenSSL_Point(void);
      |       ^~~~~~~~~~~
ssl_compat.h:51:7: error: expected declaration specifiers or '...' before string constant
   51 | void *OPENSSL_zalloc(size_t num);
      |       ^~~~~~~~~~~~~~
ssl_compat.h:51:7: error: expected declaration specifiers or '...' before numeric constant
   51 | void *OPENSSL_zalloc(size_t num);
      |       ^~~~~~~~~~~~~~
make[4]: Leaving directory '/app/openpace/src'
...
```

**Comment by frankmorgner** [comment]
which version of openssl is used?

**Comment by dominikheinz** [comment]
> which version of openssl is used?

1.1.1

**Comment by frankmorgner** [comment]
You should remove `--enable-openssl-install`, since you want to use the system's OpenSSL. This causes a confusion between the differences of 1.0.2 and 1.1.1...

**Comment by dominikheinz** [comment]
> You should remove `--enable-openssl-install`, since you want to use the system's OpenSSL. This causes a confusion between the differences of 1.0.2 and 1.1.1...

The problem remains even after removing the `--enable-openssl-install` flag. Can you reproduce the problem on your side?

**Comment by frankmorgner** [comment]
after downloading some gigabytes of data, my docker builds perfectly fine using the suggested change.

**Comment by dominikheinz** [comment]
Thanks, it was an unrelated problem on my side. Your suggested change works.
