### ISSUE TITLE
Apply the EAC to LDS personalization software

### ISSUE THREAD

**Issue by AbuHelweh** [frankmorgner/openpace#58]
Hi,

I have a task to apply the EAC to our LDS personalization software. We need to apply TA, CA, AA,PACE

Im looking for the writing part of your library in which we build the securityInfos and save in the LDS.

If you can help please advice

Many thanks

**Comment by frankmorgner** [comment]
I assume your personalization software initializes the card, but doesn't actually perform TA, CA, AA,PACE, right? So you only want to initialize the ASN.1 structures, right? This could be done with plain OpenSSL, many people also use some ASN.1 decoder/encoder that's more digestable than OpenSSL's syntax. For example, there's other software out there, which can derive code from an ASN.1 definition file. I think that should be more suitable for your use case.
