### ISSUE TITLE
Certificate not verified

### ISSUE THREAD

**Issue by szcsdev** [frankmorgner/openpace#62]
### Expected behaviour

What should happen?
I use the command cvc-print.exe -c certfile and after i get an error like this

[ERROR] (ta_lib.c:212 ) Could not verify certificate's validity period
certificate not verified

I use openpace on windows 11
How can i disable this error message, or how can i disable certificate validation check?
Thank you

### Actual behaviour

What happens instead?

### Steps to reproduce

1. 
2. 
3. 

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Paste Log output with less than 10 lines here```

**Comment by frankmorgner** [comment]
That was not possible. I've just added a `--disable-cvc-verification` to cvc-print to implement this
