### ISSUE TITLE
how to generate k_pi from k?

### ISSUE THREAD

**Issue by Johann356** [frankmorgner/openpace#65]
### Expected behaviour

What should happen?

### Actual behaviour

What happens instead?

### Steps to reproduce

1. 
2. 
3. 

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Paste Log output with less than 10 lines here```

**Comment by frankmorgner** [comment]
This is done in `PACE_STEP1_enc_nonce()` or `PACE_STEP2_dec_nonce()` respectively.

**Comment by Johann356** [comment]
Hello, I am implementing the PACE protocal in c++. I maybe figured out part of the protocal, sent the data I think should be proper but the response from the chip was negative. Can I tell you about my thought and could you please help correct the possible mistakes in my steps?
&nbsp;


照妖镜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Frank ***@***.***&gt;; 
发送时间: 2024年4月30日(星期二) 下午2:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [frankmorgner/openpace] how to generate k_pi from k? (Issue #65)














 
This is done in PACE_STEP1_enc_nonce() or PACE_STEP2_dec_nonce() respectively.

**Comment by frankmorgner** [comment]
Sorry, I'm not available for consulting. If you want to use OpenPACE in your application, you may contact me via mail.

**Comment by Johann356** [comment]
Can i ask you a question? I met a problem that the time the chip took to send me a ciphered random number is too long, while the time the chip took to compute public key is far more shorter. Is this a sign that the chip is somewhat broken? Have you been through this case? We've compared our procedure with a test sample in jmrtd, and the results in both codes are the same.




照妖镜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "frankmorgner/openpace"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月8日(星期三) 晚上8:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [frankmorgner/openpace] how to generate k_pi from k? (Issue #65)





 
Sorry, I'm not available for consulting. If you want to use OpenPACE in your application, you may contact me via mail.
